name: Deploy Frontend to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          npm run build

      - name: Install AWS CLI
        run: sudo apt-get install awscli -y

      - name: Deploy to S3
        run: |
          aws s3 sync client/dist s3://ai-image-generate01 --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
